# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dedc7cc4323a48dd064ff311a76dd6198ac06be1c8073da29f5353d3930bfc047dab01f50d9371c6a293fd3e1841f2ade9724625cc062d5dd7893e3d19c5ab29

test:
  secret_key_base: fa573e75b032ae62ccfd70b0fa3c8416592f7e4ed8ef8bfd95470513822bf0cc23750712b39adff80c61724e3b3818c1820989e76aed0b3a38eeb64c5b786292

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
